language: ruby
rvm:
  - 2.0.0
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
before_script:
  - cp config/database.yml.example config/database.yml
  - mysql -e 'create database sisfa_test'